### PR TITLE
SECENG-718: add Security Policy to open source repos

### PR DESCRIPTION
**Pull request by SCKelemen**
Security has recently published a Vulnerability Disclosure Policy. Additionally,
we have developed a process and policy for handling security issues in our open 
source repositories. This pull request introduces the Security Policy.

### CODE REVIEW

**Comment by SCKelemen** [comment]
Code Coverage tool fails with 429

**Comment by SCKelemen** [comment]
I guess I'll try again in 12 minutes

**Comment by SCKelemen** [comment]
Should there be some sort of token for CodeCov?

**Comment by hug-dev** [comment]
Hello @SCKelemen !

Not sure what is wrong with code coverage at the moment... To not block your PR and the ones to come I suggest that we disable the code coverage action for now and create an issue to investigate and re-enable it.

**Review by hug-dev — APPROVED** [review]

**Comment by hug-dev** [comment]
Wondering if you need to rebase now to make the CI pass?

**Comment by SCKelemen** [comment]
> Wondering if you need to rebase now to make the CI pass?

I think I can just rerun the ci jobs.

**Pull request merged**
